# Generated by Django 5.1 on 2024-08-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myblog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Slug"
            ),
        ),
    ]
