# Generated by Django 5.1.2 on 2024-10-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_alter_myblog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myblog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=151, null=True, verbose_name="Slug"
            ),
        ),
    ]
